/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Header from "../../components/Header";
import styles from "./styles.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Get Involved</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <img className={styles.banner} alt="Banner" src="/home/banner.svg" />
        <img
          className={styles.imageContent}
          alt="Content"
          src="/get_involved/involved.svg"
        />
        <img
          className={styles.why}
          alt="Why you should submit"
          src="why_you_should_submit.svg"
        />
      </main>

      <footer className={styles.footer}>
        <img className={styles.footerImg} alt="Footer" src="/home/footer.svg" />
      </footer>
    </div>
  );
}
