import { Lato } from "@next/font/google";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Fragment } from "react";
import "../styles/globals.css";

const latoFont = Lato({
  weight: ["100", "300", "400", "700", "900"],
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Fragment>
      <Head>
        <title>2023 Asia Architecture Design Awards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className={latoFont.className}>
        <Component {...pageProps} />
      </main>
    </Fragment>
  );
}
