import type { AppProps } from "next/app";
import Head from "next/head";
import { Fragment } from "react";
import { Provider } from "react-redux";
import { store } from "../store";
import "../styles/globals.css";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Fragment>
      <Head>
        <title>2023 Asia Architecture Design Awards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
        <link
          href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900&display=optional"
          rel="stylesheet"
        />
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=GTM-5WP8HRD"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
        
          gtag('config', 'GTM-5WP8HRD');
          `,
          }}
        ></script>
      </Head>
      <main>
        <Provider store={store}>
          <Component {...pageProps} />
        </Provider>
      </main>
    </Fragment>
  );
}
