/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <img className={styles.banner} alt="Banner" src="/home/banner.svg" />
        <img
          className={styles.overview}
          alt="Overview"
          src="/home/overview.svg"
        />

        <img className={styles.about} alt="About" src="/home/about.svg" />
        <img
          className={styles.awardCategories}
          alt="Award Categories"
          src="/home/award_categories.svg"
        />
        <img
          className={styles.timeline}
          alt="Timeline"
          src="/home/timeline.svg"
        />
        <img className={styles.purpose} alt="Purpose" src="/home/purpose.svg" />
        <img
          className={styles.why}
          alt="Why you should submit"
          src="/home/why.svg"
        />
        <img
          className={styles.aada_partners}
          alt="AADA Partners"
          src="/home/aada_partners.svg"
        />
        <img className={styles.news} alt="News" src="/home/news.svg" />
        {/* <Image
          className={styles.banner}
          src="/home/banner.svg"
          alt="Home banner"
          width={1440}
          height={905}
        /> */}
      </main>

      <footer className={styles.footer}>
        <img className={styles.footerImg} alt="Footer" src="/home/footer.svg" />
      </footer>
    </div>
  );
}
